### ISSUE TITLE
.ts vs .tsx

### ISSUE THREAD

**Issue by jvandermey** [droneshire/dealanalyzer#10]
You should generally only use .tsx extensions for files that include tsx syntax (i.e. psuedo dom elements that get transpiled to actual ts code). Typically, this also wouldn't go in the components dir since it's just a helper and doesn't proved a component. 

https://github.com/droneshire/dealanalyzer/blob/42c14590838684bfc521270ac0ea08dae8c975ba/src/components/Property.tsx#L1

**Comment by droneshire** [comment]
Fair point. I think I originally thought there might be some actual dom elements generated here and just didn't go back and change.

**Comment by droneshire** [comment]
[](url)
