### ISSUE TITLE
Partial types

### ISSUE THREAD

**Issue by jvandermey** [droneshire/dealanalyzer#11]
Rather than using any here and wiping out any type information, check out the `Partial` typescript helper [here](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)

https://github.com/droneshire/dealanalyzer/blob/42c14590838684bfc521270ac0ea08dae8c975ba/src/components/Property.tsx#L36

**Comment by droneshire** [comment]
Nice. Also is there a better native way of assigning these? In python this could be all done in a for loop.

**Comment by droneshire** [comment]
Also, does this actually return a `Property` object? Is the dictionary equivalent to an instance?

**Comment by jvandermey** [comment]
Sorry, forgot to come back to these. You may have already figured this out, but the type interfaces are just hints, they aren't real types. Javascript does (sort of) support classes, but ultimately everything (even class instances and things like arrays) are just objects (like a dict, but a little looser). So this just returns an object that adheres to that interface. It can still have more attributes on it as well, as long as it satisfies the interface.

On the note of arrays being object, you can do things like this without errors (since JS doesn't throw errors for missing object key access, it just returns undefined).

```js
const foo= [1, 2];
console.log(foo[1])
>> 2
console.log(foo[2])
>> undefined
console.log(foo["bar"])
>> undefined
```
